// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PushNotification.Context;

namespace PushNotification.Migrations
{
    [DbContext(typeof(PushDBContext))]
    [Migration("20190811092034_icon")]
    partial class icon
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PushNotification.Models.Notifications", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<string>("Reserve1");

                    b.Property<string>("Reserve2");

                    b.Property<string>("Reserve3");

                    b.Property<string>("attach1");

                    b.Property<string>("attach2");

                    b.Property<string>("attach3");

                    b.Property<string>("attach4");

                    b.Property<string>("attach5");

                    b.Property<DateTime>("datetime");

                    b.Property<int>("icon");

                    b.Property<Guid>("keyuser");

                    b.Property<bool>("status");

                    b.Property<int>("type");

                    b.Property<string>("user");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
